apiVersion: v1
kind: Service
metadata:
  name:  $PROJECT_NAME
  labels:
    app: $PROJECT_NAME
##spec for Service
spec: 
  type: ClusterIP
  selector:
    app: $PROJECT_NAME
  ##accepts external requests by assinging the service an external ip adress
  ports:
    - protocol: TCP
      port : 3003
      #to wich pod it should forward the 
      targetPort: 3003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: static-files-service
spec:
  selector:
    app: $PROJECT_NAME
  ports:
  - name: http
    port: 80
    targetPort: 80
