apiVersion: v1
kind: Service
metadata:
  name:  $PROJECT_NAME
  labels:
    app: $PROJECT_NAME
##spec for Service
spec: 
  type: ClusterIP
  selector:
    app: $PROJECT_NAME
  ##accepts external requests by assinging the service an external ip adress
  ports:
    - name: http
      protocol: TCP
      port: 3003
      targetPort: 3003
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

